# Stage: Dev 
FROM node:22-slim


RUN npm install -g pnpm

WORKDIR /app


COPY entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]


# Expose port Vite dev server
EXPOSE 5173

# Chạy Vite server với host 0.0.0.0 để container có thể truy cập
CMD ["pnpm", "run", "dev", "--", "--host"]
