# Sử dụng image dựa trên Debian
FROM node:22-slim

WORKDIR /app

# ----> THÊM DÒNG NÀY ĐỂ CÀI PNPM <----
RUN npm install -g pnpm

# Copy script vào thư mục /app
COPY entrypoint.sh .

# Cấp quyền cho script ở đúng đường dẫn /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Chỉ định entrypoint bằng đường dẫn tuyệt đối
ENTRYPOINT ["/app/entrypoint.sh"]

# Lệnh mặc định sẽ được truyền cho entrypoint
CMD ["pnpm", "run", "dev", "--", "--host"]