version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Dockerfile production cho Flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=production
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=myshop
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:5000 "app.main:app"

  frontend:
    build:
      context: ./frontend
      # 1. Trỏ tới Dockerfile dành cho development
      dockerfile: Dockerfile.dev
    ports:
      # 2. Mở port 5173 của Vite dev server
      - "5173:5173"
    # 3. Thêm volumes để đồng bộ code và bật hot-reload
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myshop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
