services:
  # --- Dịch vụ Backend ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      # Mount source code để bật hot-reload cho Python
      - ./backend:/app
    environment:
      # Sử dụng FLASK_DEBUG=1 để bật chế độ debug và reloader của Flask
      - FLASK_DEBUG=1

      # Biến môi trường để kết nối tới service 'db'
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=myshop
    depends_on:
      # Đảm bảo service 'db' khởi động xong trước khi 'backend' khởi động
      - db

  # --- Dịch vụ Frontend ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      # Giúp xác định thứ tự khởi động, frontend phụ thuộc vào backend
      - backend

  # --- Dịch vụ Database (MỚI) ---
  db:
    # Sử dụng image MySQL phiên bản 8
    image: mysql:8.0
    # Cấu hình credentials cho database
    # Các giá trị này PHẢI khớp với các biến MYSQL_* của backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myshop
    ports:
      # Mở cổng 3306 để có thể kết nối vào DB từ máy thật
      # bằng các công cụ như DBeaver, MySQL Workbench để debug
      - "3306:3306"
    volumes:
      # Sử dụng named volume để dữ liệu DB không bị mất
      # mỗi khi container được tạo lại
      - mysql_data:/var/lib/mysql

# --- Định nghĩa Named Volume ---
# Khai báo volume được sử dụng bởi service 'db'
volumes:
  mysql_data:
