"""init full tables - fixed nullable

Revision ID: 2b170ec7a29c
Revises: 
Create Date: 2025-10-31 03:40:01.852512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b170ec7a29c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_don_hang', sa.String(length=25), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=True),
    sa.Column('dia_chi_id', sa.Integer(), nullable=True),
    sa.Column('ten_nguoi_nhan', sa.String(length=50), nullable=False),
    sa.Column('so_dien_thoai_nguoi_nhan', sa.String(length=15), nullable=False),
    sa.Column('dia_chi_giao', sa.String(length=500), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHO_XAC_NHAN', 'DA_XAC_NHAN', 'DANG_GIAO_HANG', 'HOAN_THANH', 'DA_HUY', 'YEU_CAU_TRA_HANG', 'DA_TRA_HANG', name='trangthaidonhangenum'), nullable=False),
    sa.Column('phi_van_chuyen', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('giam_gia', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.CheckConstraint('giam_gia >= 0', name='ck_giamgia'),
    sa.CheckConstraint('phi_van_chuyen >= 0', name='ck_phivanchuyen'),
    sa.ForeignKeyConstraint(['dia_chi_id'], ['dia_chi.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('don_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_don_hang_ma_don_hang'), ['ma_don_hang'], unique=True)
        batch_op.create_index(batch_op.f('ix_don_hang_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)

    op.create_table('chi_tiet_don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=False),
    sa.Column('bien_the_san_pham_id', sa.Integer(), nullable=True),
    sa.Column('ten_san_pham_luc_mua', sa.String(length=255), nullable=False),
    sa.Column('ten_bien_the_luc_mua', sa.String(length=150), nullable=True),
    sa.Column('don_gia_luc_mua', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('so_luong', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('don_gia_luc_mua >= 0', name='ck_dongia_positive'),
    sa.CheckConstraint('so_luong > 0', name='ck_ctdh_so_luong'),
    sa.ForeignKeyConstraint(['bien_the_san_pham_id'], ['bien_the_san_pham.id'], ),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chi_tiet_don_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_don_hang_bien_the_san_pham_id'), ['bien_the_san_pham_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chi_tiet_don_hang_don_hang_id'), ['don_hang_id'], unique=False)

    op.create_table('chi_tiet_gio_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gio_hang_id', sa.Integer(), nullable=False),
    sa.Column('bien_the_san_pham_id', sa.Integer(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.Column('ngay_them', sa.DateTime(), nullable=True),
    sa.CheckConstraint('so_luong >= 1', name='ck_so_luong_positive'),
    sa.ForeignKeyConstraint(['bien_the_san_pham_id'], ['bien_the_san_pham.id'], ),
    sa.ForeignKeyConstraint(['gio_hang_id'], ['gio_hang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gio_hang_id', 'bien_the_san_pham_id', name='uq_giohang_bienthe')
    )
    with op.batch_alter_table('chi_tiet_gio_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_gio_hang_bien_the_san_pham_id'), ['bien_the_san_pham_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chi_tiet_gio_hang_gio_hang_id'), ['gio_hang_id'], unique=False)
        batch_op.create_index('ix_giohang_bienthe', ['gio_hang_id', 'bien_the_san_pham_id'], unique=False)

    op.create_table('hinh_anh_san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_the_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('la_anh_dai_dien', sa.Boolean(), nullable=False),
    sa.Column('rep_key', sa.Integer(), sa.Computed('CASE WHEN la_anh_dai_dien = 1 THEN bien_the_id ELSE NULL END', ), nullable=True),
    sa.CheckConstraint('la_anh_dai_dien IN (0, 1)', name='ck_la_anh_dai_dien_bool'),
    sa.ForeignKeyConstraint(['bien_the_id'], ['bien_the_san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hinh_anh_san_pham', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hinh_anh_san_pham_bien_the_id'), ['bien_the_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hinh_anh_san_pham_public_id'), ['public_id'], unique=True)
        batch_op.create_index('uq_bienthe_anhdaidien', ['rep_key'], unique=True)

    op.create_table('thanh_toan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=False),
    sa.Column('so_tien', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('phuong_thuc', sa.Enum('COD', 'VNPAY_QR', 'VNPAY_EWALLET', 'KHAC', name='phuongthucthanhtoanenum'), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHO_THANH_TOAN', 'DA_THANH_TOAN', 'THAT_BAI', 'DA_HOAN_TIEN', name='trangthaithanhtoanenum'), nullable=False),
    sa.Column('ma_giao_dich_ben_thu_3', sa.String(length=255), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.CheckConstraint('so_tien >= 0', name='ck_thanhtoan_so_tien'),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('don_hang_id')
    )
    with op.batch_alter_table('thanh_toan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thanh_toan_ma_giao_dich_ben_thu_3'), ['ma_giao_dich_ben_thu_3'], unique=False)

    op.create_table('danh_gia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chi_tiet_don_hang_id', sa.Integer(), nullable=False),
    sa.Column('san_pham_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('diem_danh_gia', sa.Integer(), nullable=False),
    sa.Column('binh_luan', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.Enum('DA_DUYET', 'BI_TU_CHOI', name='trangthaidanhgiaenum'), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.CheckConstraint('diem_danh_gia >= 1 AND diem_danh_gia <= 5', name='check_diem_danh_gia_range'),
    sa.ForeignKeyConstraint(['chi_tiet_don_hang_id'], ['chi_tiet_don_hang.id'], ),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['san_pham_id'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chi_tiet_don_hang_id'),
    sa.UniqueConstraint('san_pham_id', 'nguoi_dung_id', name='uq_user_sanpham_danhgia')
    )
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.create_index('idx_trang_thai_danhgia', ['trang_thai'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_san_pham_id'), ['san_pham_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danh_gia_san_pham_id'))
        batch_op.drop_index(batch_op.f('ix_danh_gia_nguoi_dung_id'))
        batch_op.drop_index('idx_trang_thai_danhgia')

    op.drop_table('danh_gia')
    with op.batch_alter_table('thanh_toan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thanh_toan_ma_giao_dich_ben_thu_3'))

    op.drop_table('thanh_toan')
    with op.batch_alter_table('hinh_anh_san_pham', schema=None) as batch_op:
        batch_op.drop_index('uq_bienthe_anhdaidien')
        batch_op.drop_index(batch_op.f('ix_hinh_anh_san_pham_public_id'))
        batch_op.drop_index(batch_op.f('ix_hinh_anh_san_pham_bien_the_id'))

    op.drop_table('hinh_anh_san_pham')
    with op.batch_alter_table('chi_tiet_gio_hang', schema=None) as batch_op:
        batch_op.drop_index('ix_giohang_bienthe')
        batch_op.drop_index(batch_op.f('ix_chi_tiet_gio_hang_gio_hang_id'))
        batch_op.drop_index(batch_op.f('ix_chi_tiet_gio_hang_bien_the_san_pham_id'))

    op.drop_table('chi_tiet_gio_hang')
    with op.batch_alter_table('chi_tiet_don_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_don_hang_don_hang_id'))
        batch_op.drop_index(batch_op.f('ix_chi_tiet_don_hang_bien_the_san_pham_id'))

    op.drop_table('chi_tiet_don_hang')
    with op.batch_alter_table('don_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_don_hang_nguoi_dung_id'))
        batch_op.drop_index(batch_op.f('ix_don_hang_ma_don_hang'))

    op.drop_table('don_hang')
    # ### end Alembic commands ###
