"""Build lai phan models

Revision ID: 883a600829d4
Revises: a64e81284425
Create Date: 2025-10-16 15:09:10.186996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '883a600829d4'
down_revision = 'a64e81284425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.drop_column('tieu_de')

    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_ma_nguoi_dung'))
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_ten_dang_nhap'))
        batch_op.drop_column('ma_nguoi_dung')
        batch_op.drop_column('ten_dang_nhap')

    with op.batch_alter_table('thanh_toan', schema=None) as batch_op:
        batch_op.alter_column('so_tien',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thanh_toan', schema=None) as batch_op:
        batch_op.alter_column('so_tien',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=mysql.DECIMAL(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ten_dang_nhap', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('ma_nguoi_dung', mysql.VARCHAR(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_nguoi_dung_ten_dang_nhap'), ['ten_dang_nhap'], unique=True)
        batch_op.create_index(batch_op.f('ix_nguoi_dung_ma_nguoi_dung'), ['ma_nguoi_dung'], unique=True)

    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tieu_de', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
