"""Initial migration

Revision ID: a64e81284425
Revises: 
Create Date: 2025-10-14 06:55:36.901522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64e81284425'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danh_muc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_danh_muc', sa.String(length=10), nullable=False),
    sa.Column('ten_danh_muc', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_danh_muc')
    )
    with op.batch_alter_table('danh_muc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_danh_muc_ma_danh_muc'), ['ma_danh_muc'], unique=True)
        batch_op.create_index(batch_op.f('ix_danh_muc_slug'), ['slug'], unique=True)

    op.create_table('nguoi_dung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_nguoi_dung', sa.String(length=20), nullable=False),
    sa.Column('ho_ten', sa.String(length=100), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('ten_dang_nhap', sa.String(length=50), nullable=False),
    sa.Column('mat_khau_hash', sa.String(length=256), nullable=False),
    sa.Column('vai_tro', sa.Enum('KHACH_HANG', 'QUAN_TRI_VIEN', name='vaitronguoidung'), nullable=False),
    sa.Column('trang_thai', sa.Enum('KICH_HOAT', 'KHOA', name='trangthainguoidung'), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nguoi_dung_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_nguoi_dung_ma_nguoi_dung'), ['ma_nguoi_dung'], unique=True)
        batch_op.create_index(batch_op.f('ix_nguoi_dung_so_dien_thoai'), ['so_dien_thoai'], unique=True)
        batch_op.create_index(batch_op.f('ix_nguoi_dung_ten_dang_nhap'), ['ten_dang_nhap'], unique=True)

    op.create_table('thuong_hieu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_thuong_hieu', sa.String(length=20), nullable=False),
    sa.Column('ten_thuong_hieu', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_thuong_hieu')
    )
    with op.batch_alter_table('thuong_hieu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thuong_hieu_ma_thuong_hieu'), ['ma_thuong_hieu'], unique=True)
        batch_op.create_index(batch_op.f('ix_thuong_hieu_slug'), ['slug'], unique=True)

    op.create_table('dia_chi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('ten_nguoi_nhan', sa.String(length=100), nullable=False),
    sa.Column('so_dien_thoai', sa.String(length=15), nullable=False),
    sa.Column('dia_chi_cu_the', sa.String(length=255), nullable=False),
    sa.Column('phuong_xa', sa.String(length=100), nullable=False),
    sa.Column('tinh_thanh', sa.String(length=100), nullable=False),
    sa.Column('ma_buu_dien', sa.String(length=20), nullable=True),
    sa.Column('la_mac_dinh', sa.Boolean(), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dia_chi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dia_chi_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)

    op.create_table('don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_don_hang', sa.String(length=50), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHO_XAC_NHAN', 'DA_XAC_NHAN', 'DANG_GIAO_HANG', 'HOAN_THANH', 'DA_HUY', 'YEU_CAU_TRA_HANG', 'DA_TRA_HANG', name='trangthaidonhang'), nullable=False),
    sa.Column('tam_tinh', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('phi_van_chuyen', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('giam_gia', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tong_tien', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ten_nguoi_nhan', sa.String(length=100), nullable=True),
    sa.Column('so_dien_thoai_nhan', sa.String(length=15), nullable=True),
    sa.Column('dia_chi_giao_hang', sa.String(length=500), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('don_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_don_hang_ma_don_hang'), ['ma_don_hang'], unique=True)
        batch_op.create_index(batch_op.f('ix_don_hang_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)

    op.create_table('gio_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nguoi_dung_id')
    )
    op.create_table('san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.String(length=50), nullable=False),
    sa.Column('danh_muc_id', sa.Integer(), nullable=False),
    sa.Column('thuong_hieu_id', sa.Integer(), nullable=False),
    sa.Column('ten_san_pham', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('thong_so_ky_thuat', sa.JSON(), nullable=True),
    sa.Column('trang_thai', sa.Enum('DANG_BAN', 'AN', 'HET_HANG', name='trangthaisanpham'), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['danh_muc_id'], ['danh_muc.id'], ),
    sa.ForeignKeyConstraint(['thuong_hieu_id'], ['thuong_hieu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('san_pham', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_san_pham_danh_muc_id'), ['danh_muc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_san_pham_ma_san_pham'), ['ma_san_pham'], unique=True)
        batch_op.create_index(batch_op.f('ix_san_pham_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_san_pham_ten_san_pham'), ['ten_san_pham'], unique=False)
        batch_op.create_index(batch_op.f('ix_san_pham_thuong_hieu_id'), ['thuong_hieu_id'], unique=False)

    op.create_table('bien_the_san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('san_pham_goc_id', sa.Integer(), nullable=False),
    sa.Column('ma_sku', sa.String(length=120), nullable=False),
    sa.Column('ten_bien_the', sa.String(length=100), nullable=True),
    sa.Column('gia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gia_khuyen_mai', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gia_nhap_vao', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('so_luong_ton', sa.Integer(), nullable=False),
    sa.CheckConstraint('gia > 0', name='check_gia_positive'),
    sa.CheckConstraint('gia_khuyen_mai IS NULL OR (gia_khuyen_mai > 0 AND gia_khuyen_mai < gia)', name='check_gia_khuyen_mai_valid'),
    sa.CheckConstraint('so_luong_ton >= 0', name='check_so_luong_ton_non_negative'),
    sa.ForeignKeyConstraint(['san_pham_goc_id'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bien_the_san_pham', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bien_the_san_pham_ma_sku'), ['ma_sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_bien_the_san_pham_san_pham_goc_id'), ['san_pham_goc_id'], unique=False)

    op.create_table('thanh_toan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=False),
    sa.Column('so_tien', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('phuong_thuc', sa.Enum('COD', 'CHUYEN_KHOAN', 'VNPAY', name='phuongthucthanhtoan'), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHO_THANH_TOAN', 'DA_THANH_TOAN', 'THAT_BAI', 'DA_HOAN_TIEN', name='trangthaithanhtoan'), nullable=False),
    sa.Column('ma_giao_dich_ben_thu_3', sa.String(length=255), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('don_hang_id')
    )
    with op.batch_alter_table('thanh_toan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thanh_toan_ma_giao_dich_ben_thu_3'), ['ma_giao_dich_ben_thu_3'], unique=False)

    op.create_table('chi_tiet_don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=False),
    sa.Column('bien_the_san_pham_id', sa.Integer(), nullable=True),
    sa.Column('sku_luc_mua', sa.String(length=150), nullable=False),
    sa.Column('ten_san_pham_luc_mua', sa.String(length=255), nullable=False),
    sa.Column('ten_bien_the_luc_mua', sa.String(length=150), nullable=True),
    sa.Column('don_gia_luc_mua', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bien_the_san_pham_id'], ['bien_the_san_pham.id'], ),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chi_tiet_don_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_don_hang_don_hang_id'), ['don_hang_id'], unique=False)

    op.create_table('chi_tiet_gio_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gio_hang_id', sa.Integer(), nullable=False),
    sa.Column('bien_the_san_pham_id', sa.Integer(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.Column('ngay_them', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bien_the_san_pham_id'], ['bien_the_san_pham.id'], ),
    sa.ForeignKeyConstraint(['gio_hang_id'], ['gio_hang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chi_tiet_gio_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_gio_hang_bien_the_san_pham_id'), ['bien_the_san_pham_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chi_tiet_gio_hang_gio_hang_id'), ['gio_hang_id'], unique=False)

    op.create_table('hinh_anh_san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_the_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('la_anh_dai_dien', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bien_the_id'], ['bien_the_san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hinh_anh_san_pham', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hinh_anh_san_pham_bien_the_id'), ['bien_the_id'], unique=False)

    op.create_table('danh_gia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chi_tiet_don_hang_id', sa.Integer(), nullable=False),
    sa.Column('san_pham_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('diem_danh_gia', sa.Integer(), nullable=False),
    sa.Column('tieu_de', sa.String(length=255), nullable=True),
    sa.Column('binh_luan', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.Enum('DA_DUYET', 'BI_TU_CHOI', name='trangthaidanhgia'), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.CheckConstraint('diem_danh_gia >= 1 AND diem_danh_gia <= 5', name='check_diem_danh_gia_range'),
    sa.ForeignKeyConstraint(['chi_tiet_don_hang_id'], ['chi_tiet_don_hang.id'], ),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['san_pham_id'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chi_tiet_don_hang_id')
    )
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_danh_gia_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_san_pham_id'), ['san_pham_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danh_gia_san_pham_id'))
        batch_op.drop_index(batch_op.f('ix_danh_gia_nguoi_dung_id'))

    op.drop_table('danh_gia')
    with op.batch_alter_table('hinh_anh_san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hinh_anh_san_pham_bien_the_id'))

    op.drop_table('hinh_anh_san_pham')
    with op.batch_alter_table('chi_tiet_gio_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_gio_hang_gio_hang_id'))
        batch_op.drop_index(batch_op.f('ix_chi_tiet_gio_hang_bien_the_san_pham_id'))

    op.drop_table('chi_tiet_gio_hang')
    with op.batch_alter_table('chi_tiet_don_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_don_hang_don_hang_id'))

    op.drop_table('chi_tiet_don_hang')
    with op.batch_alter_table('thanh_toan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thanh_toan_ma_giao_dich_ben_thu_3'))

    op.drop_table('thanh_toan')
    with op.batch_alter_table('bien_the_san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bien_the_san_pham_san_pham_goc_id'))
        batch_op.drop_index(batch_op.f('ix_bien_the_san_pham_ma_sku'))

    op.drop_table('bien_the_san_pham')
    with op.batch_alter_table('san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_san_pham_thuong_hieu_id'))
        batch_op.drop_index(batch_op.f('ix_san_pham_ten_san_pham'))
        batch_op.drop_index(batch_op.f('ix_san_pham_slug'))
        batch_op.drop_index(batch_op.f('ix_san_pham_ma_san_pham'))
        batch_op.drop_index(batch_op.f('ix_san_pham_danh_muc_id'))

    op.drop_table('san_pham')
    op.drop_table('gio_hang')
    with op.batch_alter_table('don_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_don_hang_nguoi_dung_id'))
        batch_op.drop_index(batch_op.f('ix_don_hang_ma_don_hang'))

    op.drop_table('don_hang')
    with op.batch_alter_table('dia_chi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dia_chi_nguoi_dung_id'))

    op.drop_table('dia_chi')
    with op.batch_alter_table('thuong_hieu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thuong_hieu_slug'))
        batch_op.drop_index(batch_op.f('ix_thuong_hieu_ma_thuong_hieu'))

    op.drop_table('thuong_hieu')
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_ten_dang_nhap'))
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_so_dien_thoai'))
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_ma_nguoi_dung'))
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_email'))

    op.drop_table('nguoi_dung')
    with op.batch_alter_table('danh_muc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danh_muc_slug'))
        batch_op.drop_index(batch_op.f('ix_danh_muc_ma_danh_muc'))

    op.drop_table('danh_muc')
    # ### end Alembic commands ###
