"""Initial models

Revision ID: b97f0f7d23f6
Revises: 
Create Date: 2025-10-18 12:59:02.789919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97f0f7d23f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bien_the_san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('san_pham_id', sa.Integer(), nullable=False),
    sa.Column('ma_sku', sa.String(length=120), nullable=False),
    sa.Column('ten_bien_the', sa.String(length=100), nullable=True),
    sa.Column('gia', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gia_khuyen_mai', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gia_nhap_vao', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('so_luong_ton', sa.Integer(), nullable=False),
    sa.CheckConstraint('gia > 0', name='check_gia_positive'),
    sa.CheckConstraint('gia_khuyen_mai IS NULL OR (gia_khuyen_mai > 0 AND gia_khuyen_mai < gia)', name='check_gia_khuyen_mai_valid'),
    sa.CheckConstraint('so_luong_ton >= 0', name='check_so_luong_ton_non_negative'),
    sa.ForeignKeyConstraint(['san_pham_id'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bien_the_san_pham', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bien_the_san_pham_ma_sku'), ['ma_sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_bien_the_san_pham_san_pham_id'), ['san_pham_id'], unique=False)

    op.create_table('thanh_toan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=False),
    sa.Column('so_tien', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('phuong_thuc', sa.Enum('COD', 'CHUYEN_KHOAN', 'VNPAY', name='phuongthucthanhtoan'), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHO_THANH_TOAN', 'DA_THANH_TOAN', 'THAT_BAI', 'DA_HOAN_TIEN', name='trangthaithanhtoan'), nullable=False),
    sa.Column('ma_giao_dich_ben_thu_3', sa.String(length=255), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('don_hang_id')
    )
    with op.batch_alter_table('thanh_toan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thanh_toan_ma_giao_dich_ben_thu_3'), ['ma_giao_dich_ben_thu_3'], unique=False)

    op.create_table('chi_tiet_don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=False),
    sa.Column('bien_the_san_pham_id', sa.Integer(), nullable=True),
    sa.Column('sku_luc_mua', sa.String(length=150), nullable=False),
    sa.Column('ten_san_pham_luc_mua', sa.String(length=255), nullable=False),
    sa.Column('ten_bien_the_luc_mua', sa.String(length=150), nullable=True),
    sa.Column('don_gia_luc_mua', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bien_the_san_pham_id'], ['bien_the_san_pham.id'], ),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chi_tiet_don_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_don_hang_don_hang_id'), ['don_hang_id'], unique=False)

    op.create_table('chi_tiet_gio_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gio_hang_id', sa.Integer(), nullable=False),
    sa.Column('bien_the_san_pham_id', sa.Integer(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.Column('ngay_them', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bien_the_san_pham_id'], ['bien_the_san_pham.id'], ),
    sa.ForeignKeyConstraint(['gio_hang_id'], ['gio_hang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chi_tiet_gio_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_gio_hang_bien_the_san_pham_id'), ['bien_the_san_pham_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chi_tiet_gio_hang_gio_hang_id'), ['gio_hang_id'], unique=False)

    op.create_table('hinh_anh_san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_the_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('la_anh_dai_dien', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bien_the_id'], ['bien_the_san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hinh_anh_san_pham', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hinh_anh_san_pham_bien_the_id'), ['bien_the_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hinh_anh_san_pham_public_id'), ['public_id'], unique=False)

    op.create_table('danh_gia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chi_tiet_don_hang_id', sa.Integer(), nullable=False),
    sa.Column('san_pham_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('diem_danh_gia', sa.Integer(), nullable=False),
    sa.Column('binh_luan', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.Enum('DA_DUYET', 'BI_TU_CHOI', name='trangthaidanhgia'), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.CheckConstraint('diem_danh_gia >= 1 AND diem_danh_gia <= 5', name='check_diem_danh_gia_range'),
    sa.ForeignKeyConstraint(['chi_tiet_don_hang_id'], ['chi_tiet_don_hang.id'], ),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['san_pham_id'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chi_tiet_don_hang_id')
    )
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_danh_gia_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_san_pham_id'), ['san_pham_id'], unique=False)

    with op.batch_alter_table('san_pham', schema=None) as batch_op:
        batch_op.create_index('idx_sanpham_fts', ['ten_san_pham', 'mo_ta'], unique=False, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
        batch_op.create_index(batch_op.f('ix_san_pham_danh_muc_id'), ['danh_muc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_san_pham_ma_san_pham'), ['ma_san_pham'], unique=True)
        batch_op.create_index(batch_op.f('ix_san_pham_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_san_pham_ten_san_pham'), ['ten_san_pham'], unique=False)
        batch_op.create_index(batch_op.f('ix_san_pham_thuong_hieu_id'), ['thuong_hieu_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_san_pham_thuong_hieu_id'))
        batch_op.drop_index(batch_op.f('ix_san_pham_ten_san_pham'))
        batch_op.drop_index(batch_op.f('ix_san_pham_slug'))
        batch_op.drop_index(batch_op.f('ix_san_pham_ma_san_pham'))
        batch_op.drop_index(batch_op.f('ix_san_pham_danh_muc_id'))
        batch_op.drop_index('idx_sanpham_fts', mysql_prefix='FULLTEXT', mysql_with_parser='ngram')

    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danh_gia_san_pham_id'))
        batch_op.drop_index(batch_op.f('ix_danh_gia_nguoi_dung_id'))

    op.drop_table('danh_gia')
    with op.batch_alter_table('hinh_anh_san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hinh_anh_san_pham_public_id'))
        batch_op.drop_index(batch_op.f('ix_hinh_anh_san_pham_bien_the_id'))

    op.drop_table('hinh_anh_san_pham')
    with op.batch_alter_table('chi_tiet_gio_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_gio_hang_gio_hang_id'))
        batch_op.drop_index(batch_op.f('ix_chi_tiet_gio_hang_bien_the_san_pham_id'))

    op.drop_table('chi_tiet_gio_hang')
    with op.batch_alter_table('chi_tiet_don_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_don_hang_don_hang_id'))

    op.drop_table('chi_tiet_don_hang')
    with op.batch_alter_table('thanh_toan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thanh_toan_ma_giao_dich_ben_thu_3'))

    op.drop_table('thanh_toan')
    with op.batch_alter_table('bien_the_san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bien_the_san_pham_san_pham_id'))
        batch_op.drop_index(batch_op.f('ix_bien_the_san_pham_ma_sku'))

    op.drop_table('bien_the_san_pham')
    # ### end Alembic commands ###
