"""init full tables - fixed nullable

Revision ID: dfeb9a4e7e79
Revises: 
Create Date: 2025-12-02 12:08:48.025236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfeb9a4e7e79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anh_trinh_chieu',
    sa.Column('anh_trinh_chieu_id', sa.Integer(), nullable=False),
    sa.Column('tieu_de', sa.String(length=200), nullable=False),
    sa.Column('hinh_anh_url', sa.String(length=255), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('lien_ket', sa.String(length=255), nullable=True),
    sa.Column('vi_tri', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Enum('HIEU_LUC', 'KHONG_HIEU_LUC', name='trangthaianhtrinhchieuenum'), nullable=False),
    sa.PrimaryKeyConstraint('anh_trinh_chieu_id')
    )
    op.create_table('cap_do',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_cap_do', sa.String(length=5), nullable=False),
    sa.Column('ten_cap_do', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_cap_do')
    )
    with op.batch_alter_table('cap_do', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cap_do_ma_cap_do'), ['ma_cap_do'], unique=True)

    op.create_table('danh_muc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_danh_muc', sa.String(length=5), nullable=False),
    sa.Column('ten_danh_muc', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_danh_muc')
    )
    with op.batch_alter_table('danh_muc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_danh_muc_ma_danh_muc'), ['ma_danh_muc'], unique=True)

    op.create_table('nguoi_dung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_nguoi_dung', sa.String(length=20), nullable=False),
    sa.Column('ho_ten', sa.String(length=100), nullable=False),
    sa.Column('so_dien_thoai', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mat_khau_hash', sa.String(length=256), nullable=False),
    sa.Column('lan_cuoi_dang_nhap', sa.DateTime(), nullable=True),
    sa.Column('vai_tro', sa.Enum('KHACH_HANG', 'QUAN_TRI_VIEN', name='vaitronguoidungenum'), nullable=False),
    sa.Column('trang_thai', sa.Enum('KICH_HOAT', 'KHOA', name='trangthainguoidungenum'), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nguoi_dung_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_nguoi_dung_ma_nguoi_dung'), ['ma_nguoi_dung'], unique=True)
        batch_op.create_index(batch_op.f('ix_nguoi_dung_so_dien_thoai'), ['so_dien_thoai'], unique=True)

    op.create_table('nha_cung_cap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_nha_cung_cap', sa.String(length=12), nullable=False),
    sa.Column('ten_nha_cung_cap', sa.String(length=100), nullable=False),
    sa.Column('dia_chi', sa.String(length=500), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nguoi_dai_dien', sa.String(length=100), nullable=True),
    sa.Column('tai_khoan_ngan_hang', sa.String(length=50), nullable=True),
    sa.Column('ten_ngan_hang', sa.String(length=100), nullable=True),
    sa.Column('trang_thai', sa.Enum('KICH_HOAT', 'NGUNG_HOAT_DONG', name='trangthainhacungcapenum'), nullable=False),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nha_cung_cap', schema=None) as batch_op:
        batch_op.create_index('idx_nhacungcap_fts', ['ten_nha_cung_cap', 'ma_nha_cung_cap', 'nguoi_dai_dien', 'email', 'dia_chi', 'so_dien_thoai'], unique=False, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
        batch_op.create_index('idx_ten_nha_cung_cap_like', ['ten_nha_cung_cap'], unique=False)
        batch_op.create_index(batch_op.f('ix_nha_cung_cap_ma_nha_cung_cap'), ['ma_nha_cung_cap'], unique=True)

    op.create_table('thuong_hieu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_thuong_hieu', sa.String(length=5), nullable=False),
    sa.Column('ten_thuong_hieu', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_thuong_hieu')
    )
    with op.batch_alter_table('thuong_hieu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thuong_hieu_ma_thuong_hieu'), ['ma_thuong_hieu'], unique=True)

    op.create_table('dia_chi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('ten_nguoi_nhan', sa.String(length=100), nullable=False),
    sa.Column('so_dien_thoai', sa.String(length=15), nullable=False),
    sa.Column('phuong_xa', sa.String(length=100), nullable=False),
    sa.Column('tinh_thanh', sa.String(length=100), nullable=False),
    sa.Column('dia_chi_cu_the', sa.String(length=255), nullable=False),
    sa.Column('ma_buu_dien', sa.String(length=20), nullable=True),
    sa.Column('la_mac_dinh', sa.Boolean(), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dia_chi', schema=None) as batch_op:
        batch_op.create_index('idx_diachi_macdinh', ['nguoi_dung_id', 'la_mac_dinh'], unique=False)
        batch_op.create_index(batch_op.f('ix_dia_chi_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)

    op.create_table('gio_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nguoi_dung_id')
    )
    op.create_table('phieu_nhap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_nhap_id', sa.Integer(), nullable=True),
    sa.Column('ma_phieu_nhap', sa.String(length=25), nullable=True),
    sa.Column('nha_cung_cap_id', sa.Integer(), nullable=False),
    sa.Column('ngay_nhap', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_nhap_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['nha_cung_cap_id'], ['nha_cung_cap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phieu_nhap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phieu_nhap_ma_phieu_nhap'), ['ma_phieu_nhap'], unique=False)
        batch_op.create_index(batch_op.f('ix_phieu_nhap_nguoi_nhap_id'), ['nguoi_nhap_id'], unique=False)

    op.create_table('san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.String(length=24), nullable=False),
    sa.Column('danh_muc_id', sa.Integer(), nullable=False),
    sa.Column('thuong_hieu_id', sa.Integer(), nullable=False),
    sa.Column('cap_do_id', sa.Integer(), nullable=False),
    sa.Column('ten_san_pham', sa.String(length=100), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('thong_so_ky_thuat', sa.JSON(), nullable=True),
    sa.Column('so_sao_trung_binh', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('so_luong_danh_gia', sa.Integer(), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cap_do_id'], ['cap_do.id'], ),
    sa.ForeignKeyConstraint(['danh_muc_id'], ['danh_muc.id'], ),
    sa.ForeignKeyConstraint(['thuong_hieu_id'], ['thuong_hieu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('san_pham', schema=None) as batch_op:
        batch_op.create_index('idx_sanpham_fts', ['ten_san_pham', 'mo_ta'], unique=False, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
        batch_op.create_index('idx_ten_san_pham_like', ['ten_san_pham'], unique=False)
        batch_op.create_index(batch_op.f('ix_san_pham_cap_do_id'), ['cap_do_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_san_pham_danh_muc_id'), ['danh_muc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_san_pham_ma_san_pham'), ['ma_san_pham'], unique=True)
        batch_op.create_index(batch_op.f('ix_san_pham_ten_san_pham'), ['ten_san_pham'], unique=False)
        batch_op.create_index(batch_op.f('ix_san_pham_thuong_hieu_id'), ['thuong_hieu_id'], unique=False)

    op.create_table('bien_the_san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('san_pham_id', sa.Integer(), nullable=False),
    sa.Column('ten_bien_the', sa.String(length=100), nullable=False),
    sa.Column('trang_thai_kich_hoat', sa.Enum('DANG_BAN', 'SAP_BAN', 'NGUNG_BAN', name='trangthaisanphamenum'), nullable=False),
    sa.Column('gia_ban', sa.Numeric(precision=12), nullable=False),
    sa.Column('mau', sa.String(length=20), nullable=True),
    sa.Column('so_luong_nhap', sa.Integer(), nullable=False),
    sa.Column('so_luong_ban', sa.Integer(), nullable=False),
    sa.CheckConstraint('gia_ban > 0', name='check_gia_positive'),
    sa.CheckConstraint('so_luong_ban >= 0', name='check_so_luong_ban_positive'),
    sa.CheckConstraint('so_luong_nhap >= 0', name='check_so_luong_nhap_positive'),
    sa.ForeignKeyConstraint(['san_pham_id'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bien_the_san_pham', schema=None) as batch_op:
        batch_op.create_index('idx_trang_thai', ['trang_thai_kich_hoat'], unique=False)
        batch_op.create_index(batch_op.f('ix_bien_the_san_pham_san_pham_id'), ['san_pham_id'], unique=False)

    op.create_table('don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_don_hang', sa.String(length=25), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=True),
    sa.Column('dia_chi_id', sa.Integer(), nullable=True),
    sa.Column('ten_nguoi_nhan', sa.String(length=50), nullable=False),
    sa.Column('so_dien_thoai_nguoi_nhan', sa.String(length=15), nullable=False),
    sa.Column('dia_chi_giao', sa.String(length=500), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHO_XAC_NHAN', 'DA_XAC_NHAN', 'DANG_GIAO', 'DA_GIAO', 'DA_HUY', 'YEU_CAU_DOI_TRA', 'CHAP_NHAN_DOI_TRA', 'TU_CHOI_DOI_TRA', 'DA_HOAN_TIEN', name='trangthaidonhangenum'), nullable=False),
    sa.Column('phi_van_chuyen', sa.Numeric(precision=10), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('ly_do', sa.Text(), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('phi_van_chuyen >= 0', name='ck_phivanchuyen'),
    sa.ForeignKeyConstraint(['dia_chi_id'], ['dia_chi.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('don_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_don_hang_ma_don_hang'), ['ma_don_hang'], unique=True)
        batch_op.create_index(batch_op.f('ix_don_hang_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)

    op.create_table('chi_tiet_don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=False),
    sa.Column('bien_the_san_pham_id', sa.Integer(), nullable=True),
    sa.Column('ten_san_pham_luc_mua', sa.String(length=255), nullable=False),
    sa.Column('don_gia_luc_mua', sa.Numeric(precision=12), nullable=False),
    sa.Column('so_luong', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('don_gia_luc_mua >= 0', name='ck_dongia_positive'),
    sa.CheckConstraint('so_luong > 0', name='ck_ctdh_so_luong'),
    sa.ForeignKeyConstraint(['bien_the_san_pham_id'], ['bien_the_san_pham.id'], ),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chi_tiet_don_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_don_hang_bien_the_san_pham_id'), ['bien_the_san_pham_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chi_tiet_don_hang_don_hang_id'), ['don_hang_id'], unique=False)

    op.create_table('chi_tiet_gio_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gio_hang_id', sa.Integer(), nullable=False),
    sa.Column('bien_the_san_pham_id', sa.Integer(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.Column('ngay_them', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('so_luong >= 1', name='ck_so_luong_positive'),
    sa.ForeignKeyConstraint(['bien_the_san_pham_id'], ['bien_the_san_pham.id'], ),
    sa.ForeignKeyConstraint(['gio_hang_id'], ['gio_hang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gio_hang_id', 'bien_the_san_pham_id', name='uq_giohang_bienthe')
    )
    with op.batch_alter_table('chi_tiet_gio_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_gio_hang_bien_the_san_pham_id'), ['bien_the_san_pham_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chi_tiet_gio_hang_gio_hang_id'), ['gio_hang_id'], unique=False)
        batch_op.create_index('ix_giohang_bienthe', ['gio_hang_id', 'bien_the_san_pham_id'], unique=False)

    op.create_table('chi_tiet_phieu_nhap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phieu_nhap_id', sa.Integer(), nullable=True),
    sa.Column('bien_the_san_pham_id', sa.Integer(), nullable=True),
    sa.Column('so_luong', sa.Integer(), server_default='1', nullable=False),
    sa.Column('gia_nhap_tung_vat', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bien_the_san_pham_id'], ['bien_the_san_pham.id'], ),
    sa.ForeignKeyConstraint(['phieu_nhap_id'], ['phieu_nhap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chi_tiet_phieu_nhap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chi_tiet_phieu_nhap_bien_the_san_pham_id'), ['bien_the_san_pham_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chi_tiet_phieu_nhap_phieu_nhap_id'), ['phieu_nhap_id'], unique=False)

    op.create_table('hinh_anh_san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_the_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('thu_tu', sa.Integer(), nullable=False),
    sa.Column('la_anh_dai_dien', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bien_the_id'], ['bien_the_san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hinh_anh_san_pham', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hinh_anh_san_pham_bien_the_id'), ['bien_the_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hinh_anh_san_pham_public_id'), ['public_id'], unique=True)

    op.create_table('thanh_toan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=False),
    sa.Column('so_tien', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('phuong_thuc', sa.Enum('COD', 'PAYOS_QR', name='phuongthucthanhtoanenum'), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHO_THANH_TOAN', 'DA_THANH_TOAN', 'THAT_BAI', 'DA_HOAN_TIEN', name='trangthaithanhtoanenum'), nullable=False),
    sa.Column('ma_giao_dich_ben_thu_3', sa.String(length=255), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.CheckConstraint('so_tien >= 0', name='ck_thanhtoan_so_tien'),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('don_hang_id')
    )
    with op.batch_alter_table('thanh_toan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thanh_toan_ma_giao_dich_ben_thu_3'), ['ma_giao_dich_ben_thu_3'], unique=False)

    op.create_table('danh_gia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chi_tiet_don_hang_id', sa.Integer(), nullable=False),
    sa.Column('san_pham_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('diem_danh_gia', sa.Integer(), nullable=False),
    sa.Column('binh_luan', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.Enum('DA_DUYET', 'BI_TU_CHOI', name='trangthaidanhgiaenum'), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.CheckConstraint('diem_danh_gia >= 1 AND diem_danh_gia <= 5', name='check_diem_danh_gia_range'),
    sa.ForeignKeyConstraint(['chi_tiet_don_hang_id'], ['chi_tiet_don_hang.id'], ),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['san_pham_id'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chi_tiet_don_hang_id')
    )
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.create_index('idx_trang_thai_danhgia', ['trang_thai'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_danh_gia_san_pham_id'), ['san_pham_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danh_gia_san_pham_id'))
        batch_op.drop_index(batch_op.f('ix_danh_gia_nguoi_dung_id'))
        batch_op.drop_index('idx_trang_thai_danhgia')

    op.drop_table('danh_gia')
    with op.batch_alter_table('thanh_toan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thanh_toan_ma_giao_dich_ben_thu_3'))

    op.drop_table('thanh_toan')
    with op.batch_alter_table('hinh_anh_san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hinh_anh_san_pham_public_id'))
        batch_op.drop_index(batch_op.f('ix_hinh_anh_san_pham_bien_the_id'))

    op.drop_table('hinh_anh_san_pham')
    with op.batch_alter_table('chi_tiet_phieu_nhap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_phieu_nhap_phieu_nhap_id'))
        batch_op.drop_index(batch_op.f('ix_chi_tiet_phieu_nhap_bien_the_san_pham_id'))

    op.drop_table('chi_tiet_phieu_nhap')
    with op.batch_alter_table('chi_tiet_gio_hang', schema=None) as batch_op:
        batch_op.drop_index('ix_giohang_bienthe')
        batch_op.drop_index(batch_op.f('ix_chi_tiet_gio_hang_gio_hang_id'))
        batch_op.drop_index(batch_op.f('ix_chi_tiet_gio_hang_bien_the_san_pham_id'))

    op.drop_table('chi_tiet_gio_hang')
    with op.batch_alter_table('chi_tiet_don_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chi_tiet_don_hang_don_hang_id'))
        batch_op.drop_index(batch_op.f('ix_chi_tiet_don_hang_bien_the_san_pham_id'))

    op.drop_table('chi_tiet_don_hang')
    with op.batch_alter_table('don_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_don_hang_nguoi_dung_id'))
        batch_op.drop_index(batch_op.f('ix_don_hang_ma_don_hang'))

    op.drop_table('don_hang')
    with op.batch_alter_table('bien_the_san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bien_the_san_pham_san_pham_id'))
        batch_op.drop_index('idx_trang_thai')

    op.drop_table('bien_the_san_pham')
    with op.batch_alter_table('san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_san_pham_thuong_hieu_id'))
        batch_op.drop_index(batch_op.f('ix_san_pham_ten_san_pham'))
        batch_op.drop_index(batch_op.f('ix_san_pham_ma_san_pham'))
        batch_op.drop_index(batch_op.f('ix_san_pham_danh_muc_id'))
        batch_op.drop_index(batch_op.f('ix_san_pham_cap_do_id'))
        batch_op.drop_index('idx_ten_san_pham_like')
        batch_op.drop_index('idx_sanpham_fts', mysql_prefix='FULLTEXT', mysql_with_parser='ngram')

    op.drop_table('san_pham')
    with op.batch_alter_table('phieu_nhap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phieu_nhap_nguoi_nhap_id'))
        batch_op.drop_index(batch_op.f('ix_phieu_nhap_ma_phieu_nhap'))

    op.drop_table('phieu_nhap')
    op.drop_table('gio_hang')
    with op.batch_alter_table('dia_chi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dia_chi_nguoi_dung_id'))
        batch_op.drop_index('idx_diachi_macdinh')

    op.drop_table('dia_chi')
    with op.batch_alter_table('thuong_hieu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thuong_hieu_ma_thuong_hieu'))

    op.drop_table('thuong_hieu')
    with op.batch_alter_table('nha_cung_cap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nha_cung_cap_ma_nha_cung_cap'))
        batch_op.drop_index('idx_ten_nha_cung_cap_like')
        batch_op.drop_index('idx_nhacungcap_fts', mysql_prefix='FULLTEXT', mysql_with_parser='ngram')

    op.drop_table('nha_cung_cap')
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_so_dien_thoai'))
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_ma_nguoi_dung'))
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_email'))

    op.drop_table('nguoi_dung')
    with op.batch_alter_table('danh_muc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danh_muc_ma_danh_muc'))

    op.drop_table('danh_muc')
    with op.batch_alter_table('cap_do', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cap_do_ma_cap_do'))

    op.drop_table('cap_do')
    op.drop_table('anh_trinh_chieu')
    # ### end Alembic commands ###
