"""Initial migration

Revision ID: e9b593be4ffc
Revises: 
Create Date: 2025-10-13 06:46:39.124054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b593be4ffc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nguoi_dung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('ten_dang_nhap', sa.String(length=80), nullable=False),
    sa.Column('mat_khau_bam', sa.String(length=256), nullable=False),
    sa.Column('vai_tro', sa.String(length=20), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nguoi_dung_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_nguoi_dung_ten_dang_nhap'), ['ten_dang_nhap'], unique=True)

    op.create_table('san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.String(length=100), nullable=False),
    sa.Column('ten', sa.String(length=200), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('gia', sa.Float(), nullable=False),
    sa.Column('so_luong_ton', sa.Integer(), nullable=False),
    sa.Column('iso', sa.String(length=50), nullable=True),
    sa.Column('do_phan_giai', sa.String(length=50), nullable=True),
    sa.Column('loai_cam_bien', sa.String(length=100), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('san_pham', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_san_pham_ma_san_pham'), ['ma_san_pham'], unique=True)
        batch_op.create_index(batch_op.f('ix_san_pham_ten'), ['ten'], unique=False)

    op.create_table('thuong_hieu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.Column('duong_dan_logo', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thuong_hieu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thuong_hieu_ten'), ['ten'], unique=True)

    op.create_table('bien_the_san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('ten_bien_the', sa.String(length=100), nullable=False),
    sa.Column('ma_sku', sa.String(length=120), nullable=False),
    sa.Column('gia', sa.Float(), nullable=False),
    sa.Column('so_luong_ton', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bien_the_san_pham', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bien_the_san_pham_ma_sku'), ['ma_sku'], unique=True)

    op.create_table('danh_gia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('ma_nguoi_dung', sa.Integer(), nullable=False),
    sa.Column('diem_danh_gia', sa.Integer(), nullable=False),
    sa.Column('binh_luan', sa.Text(), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ma_nguoi_dung'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dia_chi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_nguoi_dung', sa.Integer(), nullable=False),
    sa.Column('ten_nguoi_nhan', sa.String(length=100), nullable=False),
    sa.Column('so_dien_thoai', sa.String(length=20), nullable=False),
    sa.Column('dia_chi_cu_the', sa.String(length=255), nullable=False),
    sa.Column('tinh', sa.String(length=100), nullable=False),
    sa.Column('phuong', sa.String(length=100), nullable=False),
    sa.Column('quoc_gia', sa.String(length=100), nullable=False),
    sa.Column('ma_buu_dien', sa.String(length=20), nullable=True),
    sa.Column('la_mac_dinh', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ma_nguoi_dung'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_don_hang', sa.String(length=50), nullable=False),
    sa.Column('ma_nguoi_dung', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHO_THANH_TOAN', 'DA_THANH_TOAN', 'DANG_GIAO_HANG', 'HOAN_THANH', 'DA_HUY', name='trangthaidonhang'), nullable=False),
    sa.Column('tong_tien', sa.Float(), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ma_nguoi_dung'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_don_hang')
    )
    op.create_table('gio_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_nguoi_dung', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_nguoi_dung'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_nguoi_dung')
    )
    op.create_table('thong_so_san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('iso', sa.String(length=100), nullable=True, comment='ISO'),
    sa.Column('toc_do_man_trap', sa.String(length=100), nullable=True, comment='Tốc Độ Màn Trập'),
    sa.Column('do_sang', sa.String(length=100), nullable=True, comment='Đo Sáng'),
    sa.Column('can_bang_trang', sa.String(length=100), nullable=True, comment='Cân Bằng Trắng'),
    sa.Column('toc_do_chup_lien_tuc', sa.String(length=100), nullable=True, comment='Tốc Độ Chụp Liên Tục'),
    sa.Column('dinh_dang_cam_bien', sa.String(length=100), nullable=True, comment='Định Dạng Cảm Biến'),
    sa.Column('do_phan_giai', sa.String(length=100), nullable=True, comment='Độ Phân Giải'),
    sa.Column('kich_thuoc_anh', sa.String(length=100), nullable=True, comment='Kích Thước Ảnh'),
    sa.Column('ty_le_anh', sa.String(length=50), nullable=True, comment='Tỷ Lệ Ảnh'),
    sa.Column('loai_cam_bien', sa.String(length=100), nullable=True, comment='Loại Cảm Biến'),
    sa.Column('dinh_dang_anh', sa.String(length=100), nullable=True, comment='Định Dạng Ảnh'),
    sa.Column('chong_rung', sa.String(length=100), nullable=True, comment='Chống Rung'),
    sa.Column('ngam_ong_kinh', sa.String(length=100), nullable=True, comment='Ngàm Ống Kính'),
    sa.Column('ma_hoa_video', sa.String(length=100), nullable=True, comment='Mã Hóa Video'),
    sa.Column('do_phan_giai_video', sa.String(length=100), nullable=True, comment='Độ Phân Giải Video'),
    sa.Column('micro', sa.String(length=100), nullable=True, comment='Micro'),
    sa.Column('dinh_dang_am_thanh', sa.String(length=100), nullable=True, comment='Định Dạng Âm Thanh'),
    sa.Column('kieu_lay_net', sa.String(length=100), nullable=True, comment='Kiểu Lấy Nét'),
    sa.Column('che_do_lay_net', sa.String(length=100), nullable=True, comment='Chế Độ Lấy Nét'),
    sa.Column('so_diem_lay_net', sa.String(length=100), nullable=True, comment='Số Điểm Lấy Nét'),
    sa.Column('loai_kinh_ngam', sa.String(length=100), nullable=True, comment='Loại kính ngắm'),
    sa.Column('dac_tinh_man_hinh', sa.String(length=200), nullable=True, comment='Đặc Tính Màn Hình'),
    sa.Column('do_phan_giai_man_hinh', sa.String(length=100), nullable=True, comment='Độ Phân Giải Màn Hình'),
    sa.Column('kich_thuoc_man_hinh', sa.String(length=50), nullable=True, comment='Kích Thước Màn Hình'),
    sa.Column('do_phong_dai_kinh_ngam', sa.String(length=50), nullable=True, comment='Độ Phóng Đại Kính Ngắm'),
    sa.Column('do_bao_phu_kinh_ngam', sa.String(length=50), nullable=True, comment='Độ Bao Phủ Kính Ngắm'),
    sa.Column('kich_thuoc_kinh_ngam', sa.String(length=50), nullable=True, comment='Kích Thước Kính Ngắm'),
    sa.Column('do_phan_giai_kinh_ngam', sa.String(length=100), nullable=True, comment='Độ Phân Giải Kính Ngắm'),
    sa.Column('den_flash', sa.String(length=100), nullable=True, comment='Đèn Flash'),
    sa.Column('che_do_flash', sa.String(length=100), nullable=True, comment='Chế Độ Flash'),
    sa.Column('toc_do_danh_den', sa.String(length=100), nullable=True, comment='Tốc Độ Đánh Đèn'),
    sa.Column('chan_ket_noi', sa.String(length=100), nullable=True, comment='Chân Kết Nối'),
    sa.Column('do_bu_sang', sa.String(length=100), nullable=True, comment='Độ Bù Sáng'),
    sa.Column('dong_bo_flash', sa.String(length=100), nullable=True, comment='Đồng Bộ Flash'),
    sa.Column('gps', sa.String(length=100), nullable=True, comment='GPS'),
    sa.Column('ket_noi_khong_day', sa.String(length=150), nullable=True, comment='Kết Nối Không Dây'),
    sa.Column('jack_cam', sa.String(length=150), nullable=True, comment='Jack Cắm'),
    sa.Column('so_khe_cam_the_nho', sa.String(length=100), nullable=True, comment='Số Khe Cắm Thẻ Nhớ'),
    sa.Column('trong_luong', sa.String(length=100), nullable=True, comment='Trọng Lượng'),
    sa.Column('kich_thuoc', sa.String(length=100), nullable=True, comment='Kích Thước'),
    sa.Column('pin', sa.String(length=100), nullable=True, comment='Pin'),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_san_pham')
    )
    op.create_table('chi_tiet_don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_don_hang', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.Column('gia_luc_mua', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ma_don_hang'], ['don_hang.id'], ),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hinh_anh_san_pham',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_bien_the_san_pham', sa.Integer(), nullable=False),
    sa.Column('duong_dan_hinh_anh', sa.String(length=512), nullable=False),
    sa.Column('van_ban_thay_the', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ma_bien_the_san_pham'], ['bien_the_san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muc_gio_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_gio_hang', sa.Integer(), nullable=False),
    sa.Column('ma_san_pham', sa.Integer(), nullable=False),
    sa.Column('so_luong', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_gio_hang'], ['gio_hang.id'], ),
    sa.ForeignKeyConstraint(['ma_san_pham'], ['san_pham.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thanh_toan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_don_hang', sa.Integer(), nullable=False),
    sa.Column('so_tien', sa.Float(), nullable=False),
    sa.Column('phuong_thuc', sa.Enum('TIEN_MAT', 'VI_DIEN_TU', name='phuongthucthanhtoan'), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHUA_THANH_TOAN', 'DA_THANH_TOAN', 'THAT_BAI', name='trangthaithanhtoan'), nullable=False),
    sa.Column('ma_giao_dich', sa.String(length=200), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_cap_nhat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ma_don_hang'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_don_hang')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thanh_toan')
    op.drop_table('muc_gio_hang')
    op.drop_table('hinh_anh_san_pham')
    op.drop_table('chi_tiet_don_hang')
    op.drop_table('thong_so_san_pham')
    op.drop_table('gio_hang')
    op.drop_table('don_hang')
    op.drop_table('dia_chi')
    op.drop_table('danh_gia')
    with op.batch_alter_table('bien_the_san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bien_the_san_pham_ma_sku'))

    op.drop_table('bien_the_san_pham')
    with op.batch_alter_table('thuong_hieu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thuong_hieu_ten'))

    op.drop_table('thuong_hieu')
    with op.batch_alter_table('san_pham', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_san_pham_ten'))
        batch_op.drop_index(batch_op.f('ix_san_pham_ma_san_pham'))

    op.drop_table('san_pham')
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_ten_dang_nhap'))
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_email'))

    op.drop_table('nguoi_dung')
    # ### end Alembic commands ###
